# Generated by Django 3.2.4 on 2021-07-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
